name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    release:
        types: [created]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Run linter
              run: pnpm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run tests
              run: echo "No tests found, skipping."

    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Install wait-on
              run: pnpm add -D wait-on -w
            - name: Build
              run: pnpm run build
            - name: Start server
              run: pnpm run start &
            - name: Wait for server
              run: pnpm exec wait-on http://localhost:8000
            - name: Run Lighthouse CI
              run: pnpm run lighthouse

    build-docker:
        if: github.event_name == 'release' && github.event.action == 'created'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
