name: Publish Docker Image

on:
    push:
        branches: ['main']

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get short SHA
              id: sha
              run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Log in to the GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                    ghcr.io/rishabh5321/wallsite:latest
                    ghcr.io/rishabh5321/wallsite:${{ steps.sha.outputs.sha }}
