name: Sync to Template Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo (wallsite)
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Destination Repo (wallsite-template)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/wallsite-template
          token: ${{ secrets.REPO_ACCESS_TOKEN }} # A PAT is required
          path: destination

      - name: Sync files from source to destination
        run: |
          # Copy all files, deleting ones that no longer exist in source
          # Crucially, exclude the src, .git, and specific workflow files
          rsync -av --delete --exclude='/src/' --exclude='.git/' --exclude='.github/workflows/publish-docker.yml' --exclude='.github/workflows/sync-template.yml' source/ destination/

      - name: Create placeholder and README for template
        run: |
          # Create src placeholder
          mkdir -p destination/src
          echo "## Add Your Wallpapers Here" > destination/src/README.md
          echo "" >> destination/src/README.md
          echo "You can upload your .jpg, .png, .gif, or .webp files directly into this folder." >> destination/src/README.md

          # Create the main README for the template repo
          cat > destination/README.md <<'EOF'
            # Your New Wallpaper Gallery

            Congratulations! Your new repository is ready. Now, let's get it online.

            ## 🚀 Step 1: Deploy Your Gallery

            Choose your preferred hosting service and follow the instructions to deploy.

            <details>
            <summary><strong>Deploying on Vercel</strong></summary>

            1.  Go to your [Vercel Dashboard](https://vercel.com/dashboard) and click **Add New...** > **Project**.
            2.  Click **Continue with GitHub** and find this repository (`my-wallpaper-gallery` or the name you chose). Click **Import**.
            3.  Vercel will automatically detect the settings. Click **Deploy**.
            4.  That's it! Your gallery will be live shortly.

            </details>

            <details>
            <summary><strong>Deploying on Netlify</strong></summary>

            1.  Go to your [Netlify Team dashboard](https://app.netlify.com) and click **Add new site** > **Import an existing project**.
            2.  Click **Deploy with GitHub** and authorize access.
            3.  Find and select this repository.
            4.  Netlify will automatically detect the build settings. Click **Deploy site**.
            5.  Your gallery will be live in a few moments.

            </details>

            ## 📥 Step 2: Add Your Wallpapers

            Once your site is live:
            1.  Go to this repository on GitHub.
            2.  Navigate to the `src` folder.
            3.  Click **Add file** > **Upload files** and upload your wallpapers.
            4.  Commit the changes. Your site will automatically update with the new images.
            EOF

      - name: Commit and push changes
        run: |
          cd destination
          if [[ -z $(git status -s) ]]; then
            echo "No changes to sync."
            exit 0
          fi
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "ci: sync from main repository"
          git push
